# Converts Twitter JSON response to a dictionary set of data to prep for Pandas
import json
import numpy as np
import pickle
import codecs

def MakeTweetDict(tweet):
	tweetDATA = list()
	tweet.get('id_str')
	tweetDATA.extend(tweet.get("id"))
	tweetDATA.extend(tweet.get("created_at"))
	tweetDATA.extend(tweet.get("text"))
	tweetDATA.extend(tweet.get("display_text_range"))
	tweetDATA.extend(tweet.get("source"))
	tweetDATA.extend(tweet.get("truncated"))
	tweetDATA.extend(tweet.get("in_reply_to_status_id"))
	tweetDATA.extend(tweet.get("in_reply_to_status_id_str"))
	tweetDATA.extend(tweet.get("in_reply_to_user_id"))
	tweetDATA.extend(tweet.get("in_reply_to_user_id_str"))
	tweetDATA.extend(tweet.get("in_reply_to_screen_name"))
	tweetDATA.extend(tweet.get("user", {}).get("id"))
	tweetDATA.extend(tweet.get("user", {}).get("id_str"))
	tweetDATA.extend(tweet.get("user", {}).get("name"))
	tweetDATA.extend(tweet.get("user", {}).get("screen_name"))
	tweetDATA.extend(tweet.get("user", {}).get("location"))
	tweetDATA.extend(tweet.get("user", {}).get("url"))
	tweetDATA.extend(tweet.get("user", {}).get("description"))
	tweetDATA.extend(tweet.get("user", {}).get("translator_type"))
	tweetDATA.extend(tweet.get("user", {}).get("protected"))
	tweetDATA.extend(tweet.get("user", {}).get("verified"))
	tweetDATA.extend(tweet.get("user", {}).get("followers_count"))
	tweetDATA.extend(tweet.get("user", {}).get("friends_count"))
	tweetDATA.extend(tweet.get("user", {}).get("listed_count"))
	tweetDATA.extend(tweet.get("user", {}).get("favourites_count"))
	tweetDATA.extend(tweet.get("user", {}).get("statuses_count"))
	tweetDATA.extend(tweet.get("user", {}).get("created_at"))
	tweetDATA.extend(tweet.get("user", {}).get("utc_offset"))
	tweetDATA.extend(tweet.get("user", {}).get("time_zone"))
	tweetDATA.extend(tweet.get("user", {}).get("geo_enabled"))
	tweetDATA.extend(tweet.get("user", {}).get("lang"))
	tweetDATA.extend(tweet.get("user", {}).get("contributors_enabled"))
	tweetDATA.extend(tweet.get("user", {}).get("is_translator"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_background_color"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_background_image_url"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_background_image_url_https"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_background_tile"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_link_color"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_sidebar_border_color"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_sidebar_fill_color"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_text_color"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_use_background_image"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_image_url"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_image_url_https"))
	tweetDATA.extend(tweet.get("user", {}).get("profile_banner_url"))
	tweetDATA.extend(tweet.get("user", {}).get("default_profile"))
	tweetDATA.extend(tweet.get("user", {}).get("default_profile_image"))
	tweetDATA.extend(tweet.get("user", {}).get("following"))
	tweetDATA.extend(tweet.get("user", {}).get("follow_request_sent"))
	tweetDATA.extend(tweet.get("user", {}).get("geo"))
	tweetDATA.extend(tweet.get("coordinates"))
	tweetDATA.extend(tweet.get("favorited"))
	tweetDATA.extend(tweet.get("retweeted"))
	tweetDATA.extend(tweet.get('entities', {}).get('hashtags'))
	tweetDATA.extend(tweet.get('entities', {}).get('urls'))
	tweetDATA.extend(tweet.get('entities', {}).get('user_mentions'))
	tweetDATA.extend(tweet.get('entities', {}).get('symbols'))
	tweetDATA.extend(tweet.get('entities', {}).get('media'))


	tweetDATA.extend(tweet.get("quote_count"))
	tweetDATA.extend(tweet.get("reply_count"))
	tweetDATA.extend(tweet.get("retweet_count"))


	if tweet.get("place") is not None:
		tweetDATA.extend(tweet.get("place", {}).get("id"))
		tweetDATA.extend(tweet.get("place", {}).get("url"))
		tweetDATA.extend(tweet.get("place", {}).get("place_type"))
		tweetDATA.extend(tweet.get("place", {}).get("name"))
		tweetDATA.extend(tweet.get("place", {}).get("full_name"))
		tweetDATA.extend(tweet.get("place", {}).get("country_code"))
		tweetDATA.extend(tweet.get("place", {}).get("bounding_box", {}).get("type"))
		tweetDATA.extend(tweet.get("place", {}).get("bounding_box", {}).get("coordinates"))
	else:
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")
		tweetDATA.extend("No Data")

	tweetDATA.extend(tweet.get("quoted_status_id_str"))
	tweetDATA.extend(tweet.get("is_quote_status"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("created_at"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("id"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("id_str"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("text"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("source"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("truncated"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("in_reply_to_status_id"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("in_reply_to_status_id_str"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("in_reply_to_user_id"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("in_reply_to_user_id_str"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("in_reply_to_screen_name"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("id"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("id_str"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("name"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("screen_name"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("location"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("url"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("description"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("translator_type"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("protected"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("verified"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("followers_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("friends_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("listed_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("favourites_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("statuses_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("created_at"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("utc_offset"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("time_zone"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("geo_enabled"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("lang"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("contributors_enabled"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("is_translator"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_background_color"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_background_image_url"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_background_image_url_https"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_background_tile"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_link_color"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_sidebar_border_color"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_sidebar_fill_color"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_text_color"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_use_background_image"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_image_url"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_image_url_https"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("profile_banner_url"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("default_profile"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("default_profile_image"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("following"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("follow_request_sent"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("user", {}).get("notifications"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("geo"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("coordinates"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("place"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("contributors"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("is_quote_status"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("quote_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("reply_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("retweet_count"))
	tweetDATA.extend(tweet.get("quoted_status", {}).get("favorite_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("created_at"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("text"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("display_text_range"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("source"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("truncated"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("in_reply_to_status_id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("in_reply_to_status_id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("in_reply_to_user_id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("in_reply_to_user_id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("in_reply_to_screen_name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("screen_name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("location"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("description"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("translator_type"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("protected"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("verified"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("followers_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("friends_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("listed_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("favourites_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("statuses_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("created_at"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("utc_offset"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("time_zone"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("geo_enabled"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("lang"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("contributors_enabled"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("is_translator"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_background_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_background_image_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_background_image_url_https"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_background_tile"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_link_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_sidebar_border_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_sidebar_fill_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_text_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_use_background_image"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_image_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_image_url_https"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("profile_banner_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("default_profile"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("default_profile_image"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("following"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("follow_request_sent"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("user", {}).get("notifications"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("created_at"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("text"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("source"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("truncated"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("in_reply_to_status_id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("in_reply_to_status_id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("in_reply_to_user_id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("in_reply_to_user_id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("in_reply_to_screen_name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("id"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("id_str"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("screen_name"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("location"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("description"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("translator_type"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("protected"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("verified"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("followers_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("friends_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("listed_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("favourites_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("statuses_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("created_at"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("utc_offset"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("time_zone"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("geo_enabled"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("lang"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("contributors_enabled"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("is_translator"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_background_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_background_image_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_background_image_url_https"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_background_tile"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_link_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_sidebar_border_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_sidebar_fill_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_text_color"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_use_background_image"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_image_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_image_url_https"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("profile_banner_url"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("default_profile"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("default_profile_image"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("following"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("follow_request_sent"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("user", {}).get("notifications"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("geo"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("coordinates"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("place"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("contributors"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("is_quote_status"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("quote_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("reply_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("retweet_count"))
	tweetDATA.extend(tweet.get("retweeted_status", {}).get("quoted_status", {}).get("favorite_count"))


	
	return tweetDICT
